package bStat.oms.com.common.enums;

/**
 * Created by Yashi Agarwal on 24-05-2017.
 */
public enum OrderStatus {
    CREATED,
    QUEUED,
    PLACED,
    MANUFACTURING_STARTED,
    PARTIAL_MANUFACTURING_STARTED,
    PREPARED,
    PARTIALLY_PREPARED,
    PACKED,
    PARTIALLY_PACKED,
    SHIPPED,
    PARTIALLY_SHIPPED,
    DELIVERED,
    PARTIALLY_DELIVERED,
    CANCELLED,
    PARTIALLY_CANCELLED,
    RETURNED,
    PARTIALLY_RETURNED
}
